name: ESLint

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPPRESSED: 'true'
        run: npx eslint . --ext .js,.jsx,.ts,.tsx
        continue-on-error: true
